# valor = 20.25892
# print(round(valor, 2))

# lista = [1, 2, 3, 4, 5, 6]
# print(len(lista))

# list2 = ['Arthur:José', 'Idade:19']
# print(len(list2))

# String = 'manipulando string '
# sub = String.replace('manipulando string', 'editando texto')
# print(sub)  # Vai imprimir 'editando texto '

# print(String + 'teste')
# print(String.count('i'))

# String1 = 'Removendo Espaço'
# print(String1.strip())


